include_guard = "RUSTLS_H"

usize_is_size_t = true

[enum]
prefix_with_name = true
rename_variants = "ScreamingSnakeCase"

[export]
include = ["rustls_tls_version"]

[defines]
"feature = read_buf" = "DEFINE_READ_BUF"
"feature = ring" = "DEFINE_RING"
"feature = aws_lc_rs" = "DEFINE_AWS_LC_RS"

[parse.expand]
crates = ["rustls-ffi"]
features = ["read_buf", "ring", "aws_lc_rs"]
