[package]
name = "rustls-ffi-tools"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rustls = { workspace = true }
hickory-resolver = { workspace = true }
tokio = { workspace = true }

[[bin]]
name = "ech_fetch"
path = "src/ech_fetch.rs"
