name: cargo-c

permissions:
  contents: read

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '15 12 * * 3'

jobs:
  cargo-c:
    name: Build+test

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          # TODO(XXX): macos.
          - os: windows-latest
            toolchain-suffix: -gnu
          - os: windows-latest
            toolchain-suffix: -msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly${{ matrix.toolchain-suffix }}

      - name: Install cargo-c
        run: cargo install cargo-c

      - run: cargo cbuild --verbose --release
      - run: cargo ctest --verbose --release
