name: rustls-ffi

permissions:
  contents: read

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '15 12 * * 3'

jobs:
  test-macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - env:
          CARGO_UNSTABLE_HTTP_REGISTRY: true
        run: make PROFILE=release test
  test-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup PATH for CL.EXE
        uses: ilammy/msvc-dev-cmd@v1
      # Remove link.exe from non-MSVC packages that interferes with MSVC link
      - run: rm "C:\Program Files\Git\usr\bin\link.exe"
      - run: rm "C:\msys64\usr\bin\link.exe"
      - run: make -f Makefile.Windows
  test-macos2:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - env:
          CARGO_UNSTABLE_HTTP_REGISTRY: true
        run: make PROFILE=release test
  test-windows2:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup PATH for CL.EXE
        uses: ilammy/msvc-dev-cmd@v1
      # Remove link.exe from non-MSVC packages that interferes with MSVC link
      - run: rm "C:\Program Files\Git\usr\bin\link.exe"
      - run: rm "C:\msys64\usr\bin\link.exe"
      - run: make -f Makefile.Windows
  test-macos3:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - env:
          CARGO_UNSTABLE_HTTP_REGISTRY: true
        run: make PROFILE=release test
  test-windows3:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup PATH for CL.EXE
        uses: ilammy/msvc-dev-cmd@v1
      # Remove link.exe from non-MSVC packages that interferes with MSVC link
      - run: rm "C:\Program Files\Git\usr\bin\link.exe"
      - run: rm "C:\msys64\usr\bin\link.exe"
      - run: make -f Makefile.Windows
