name: rustls-ffi

permissions:
  contents: read

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '15 12 * * 3'

jobs:
  build:
    name: Build+test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # test a bunch of toolchain and crypto providers on ubuntu
        cc: [ clang, gcc ]
        crypto: [ aws-lc-rs, ring ]
        cert_compression: [ off ]
        rust:
          - stable
          - beta
          - nightly
          # MSRV - keep in sync with what rustls and rustls-platform-verifier
          # consider MSRV
          - 1.64.0
        os: [ ubuntu-latest ]
        # but only stable, clang, and aws-lc-rs on macos (slower platform)
        include:
          - os: macos-latest
            cc: clang
            crypto: aws-lc-rs
            rust: stable
            cert_compression: off
          - os: macos-latest
            cc: clang
            crypto: aws-lc-rs
            rust: stable
            cert_compression: on
          - os: ubuntu-latest
            cc: clang
            crypto: aws-lc-rs
            cert_compression: on
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Setup cmake build
        run: |
          CC=${{matrix.cc}} \
          CXX=${{matrix.cc}} \
          cmake \
            -DCRYPTO_PROVIDER=${{matrix.crypto}} \
            -DCERT_COMPRESSION=${{matrix.cert_compression}} \
            -DCMAKE_BUILD_TYPE=Debug \
            ${{ matrix.os == 'macos-latest' && '-DCMAKE_OSX_DEPLOYMENT_TARGET=14.5' || '' }} \
            -S . -B build

      - name: Platform verifier connect test
        run: cmake --build build --target connect-test

      - name: Integration tests
        run: cmake --build build --target integration-test

      - name: Verify debug builds were using ASAN
        if: runner.os == 'Linux' # For 'nm'
        run: |
          nm build/tests/client | grep '__asan_init'
          nm build/tests/server | grep '__asan_init'

      - name: Build release binaries
        run: |
          cmake --build build -- clean
          CC=${{matrix.cc}} CXX=${{matrix.cc}} cmake -S . -B build -DCRYPTO_PROVIDER=${{matrix.crypto}} -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Verify release builds were not using ASAN
        if: runner.os == 'Linux' # For 'nm'
        run: |
          ! nm build/tests/client | grep '__asan_init' 
          ! nm build/tests/server | grep '__asan_init' 

  valgrind:
    name: Valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Setup cmake build
        run: cmake -S . -B build

      - run: VALGRIND=valgrind cmake --build build --target integration-test

  test-windows-cmake:
    name: Windows CMake
    runs-on: windows-latest
    strategy:
      matrix:
        crypto: [ aws-lc-rs, ring ]
        config: [ Debug, Release ]
        cert_compression: [ off ]
        include:
          - crypto: aws-lc-rs
            config: Release
            cert_compression: on
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      # For Debug builds we use ASAN, which requires a modern MSVC on $PATH
      # to provide the ASAN clang_rt.asan_*.dll runtime deps or
      # the built client/server binary will exit immediately with 
      # exit code -1073741515
      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Configure CMake
        run: |
          cmake \
            -DCRYPTO_PROVIDER="${{ matrix.crypto }}" \
            -DCERT_COMPRESSION="${{ matrix.cert_compression }}" \
            -S . -B build

      - name: Build
        run: cmake --build build --config "${{ matrix.config }}"

      - name: Integration test
        run: cmake --build build --config "${{matrix.config}}" --target integration-test

  ensure-header-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Install cbindgen
        # Pin the installed version of cbindgen so that local usage can be
        # reliably matched to CI. There can be non-semantic differences in
        # output between point releases of cbindgen that will fail this check
        # otherwise.
        run: cargo install cbindgen --force --version 0.27.0

      - run: touch src/lib.rs

      - run: cbindgen --version

      - run: cbindgen > src/rustls.h

      - run: git diff --exit-code

  docs:
    name: Check for documentation errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: cargo doc (all features)
        run: cargo doc --all-features --no-deps --workspace
        env:
          RUSTDOCFLAGS: -Dwarnings

  minver:
    name: Check minimum versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: cargo test (debug; default features; -Z minimal-versions)
        run: cargo -Z minimal-versions test --locked

      - name: cargo test (debug; ring; -Z minimal-versions)
        run: cargo -Z minimal-versions test --no-default-features --features=ring --locked

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.67.1
          components: rustfmt

      - name: Install Gersemi
        run: pip3 install gersemi

      - name: Setup cmake build
        run: cmake -S . -B build

      - name: Check formatting
        run: cmake --build build --target format-check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Check clippy (default features)
        # We allow unknown lints here because sometimes the nightly job
        # (below) will have a new lint that we want to suppress.
        # If we suppress (e.g. #![allow(clippy::arc_with_non_send_sync)]),
        # we would get an unknown-lint error from older clippy versions.
        run: cargo clippy --locked --workspace --all-targets -- -D warnings -A unknown-lints

      - name: Check clippy (ring)
        run: cargo clippy --locked --workspace --all-targets --no-default-features --features=ring -- -D warnings -A unknown-lints

  clippy-nightly-optional:
    name: Clippy nightly (optional)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Check clippy (default features)
        run: cargo clippy --locked --workspace --all-targets -- -D warnings

      - name: Check clippy (ring)
        run: cargo clippy --locked --workspace --all-targets --no-default-features --features=ring -- -D warnings

      - name: Check clippy (all features)
        # We only test --all-features on nightly, because two of the features
        # (read_buf, core_io_borrowed_buf) require nightly.
        run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings

  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clang tidy
        run: clang-tidy tests/*.c -- -I src/

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly

      - run: rustup override set "nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)"

      - run: rustup component add miri

      - run: cargo miri test
