name: rustls-ffi

permissions:
  contents: read

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '15 12 * * 3'

jobs:
  build-one:
    name: Build+test one
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - env:
          CARGO_UNSTABLE_HTTP_REGISTRY: true
        run: make CC=clang PROFILE=release test
        
  build-two:
    name: Build+test two
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - env:
          CARGO_UNSTABLE_HTTP_REGISTRY: true
        run: make CC=clang PROFILE=release test

  build-three:
    name: Build+test three
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - env:
          CARGO_UNSTABLE_HTTP_REGISTRY: true
        run: make CC=clang PROFILE=release test

  build-four:
    name: Build+test four
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - env:
          CARGO_UNSTABLE_HTTP_REGISTRY: true
        run: make CC=clang PROFILE=release test
