name: rustls-ffi

permissions:
  contents: read

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '15 12 * * 3'

jobs:

  test-windows-cmake-debug:
    name: Windows CMake, Debug configuration
    runs-on: windows-latest
    strategy:
      matrix:
        crypto: [ aws-lc-rs, ring ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install NASM for aws-lc-rs
        uses: ilammy/setup-nasm@v1
      - name: Configure CMake
        run: cmake -DCRYPTO_PROVIDER="${{ matrix.crypto }}" -S . -B build
      - name: Build, debug configuration
        run: cmake --build build --config Debug
      - name: Smoke test client
        env:
          RUSTLS_PLATFORM_VERIFIER: 1
        run: D:\a\rustls-ffi\rustls-ffi\build\tests\Debug\client.exe example.com 443 /
      - name: Integration test, debug configuration
        run: cargo test --no-default-features --features="${{ matrix.crypto }}" --locked --test client_server client_server_integration -- --ignored --exact
        env:
          CLIENT_BINARY: D:\a\rustls-ffi\rustls-ffi\build\tests\Debug\client.exe
          SERVER_BINARY: D:\a\rustls-ffi\rustls-ffi\build\tests\Debug\server.exe

  test-windows-cmake-release:
    name: Windows CMake, Release configuration
    runs-on: windows-latest
    strategy:
      matrix:
        crypto: [ aws-lc-rs, ring ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install NASM for aws-lc-rs
        uses: ilammy/setup-nasm@v1
      - name: Configure CMake
        run: cmake -DCRYPTO_PROVIDER="${{ matrix.crypto }}" -S . -B build
      - name: Build, release configuration
        run: cmake --build build --config Release
      - name: Integration test, release configuration
        run: cargo test --no-default-features --features="${{ matrix.crypto }}" --locked --test client_server client_server_integration -- --ignored --exact
        env:
          CLIENT_BINARY: D:\a\rustls-ffi\rustls-ffi\build\tests\Release\client.exe
          SERVER_BINARY: D:\a\rustls-ffi\rustls-ffi\build\tests\Release\server.exe
